min-players: 2

countdown-seconds: 15

lobby-spawn:
  world-name: world
  x:
  y:
  z:
  yaw: -180
  pitch: 0
arenas:
  1:
    world-name: world
    x:
    y:
    z:
    yaw: -180
    pitch: 0
  2:
    world-name: world
    x:
    y:
    z:
    yaw: -180
    pitch: 0
